/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package sr.rpc.thrift;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.12.0)", date = "2019-04-25")
public enum BankCurrency implements org.apache.thrift.TEnum {
  PLN(1),
  USD(2),
  EUR(3);

  private final int value;

  private BankCurrency(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static BankCurrency findByValue(int value) { 
    switch (value) {
      case 1:
        return PLN;
      case 2:
        return USD;
      case 3:
        return EUR;
      default:
        return null;
    }
  }
}
